### ISSUE TITLE
Suggestion: Move map plotting from basemap to cartopy

### ISSUE THREAD

**Issue by runeyosh** [metno/wxgen#45]
Hi,

We at Statkraft consider rewriting the code to use cartopy instead of basemap (module) for the following reasons:

* It's under GPL licensing, which we want to avoid including in our code
* We understand that the basemap module is getting phased out in favor of cartopy

The way we see it, this can be solved by either moving completely over to cartopy, or having the code check which module is installed and use either one. We will of course implement the cartopy support and make a pull request for this.

Any views or comments on this from you guys at Met? @tnipen

**Comment by tnipen** [comment]
I fully support this. I think moving completely over to cartopy is the best solution. Thanks for the help.
